apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
    - ssh:
        address: 192.168.0.179
        user: leader
        port: 22
        keyPath: ~/.ssh/id_rsa  # Update this with the path to your SSH key
      role: controller
    - ssh:
        address: 192.168.0.197
        user: followerone
        port: 22
        keyPath: ~/.ssh/id_rsa  # Update this with the path to your SSH key
      role: worker
    - ssh:
        address: 192.168.0.187
        user: followertwo
        port: 22
        keyPath: ~/.ssh/id_rsa  # Update this with the path to your SSH key
      role: worker
  k0s:
    version: "v1.29.4+k0s.0"

